"""Change PersonToVisit to Address

Revision ID: 2164558a9ec3
Revises: d578ee306aab
Create Date: 2025-10-12 10:53:59.477510

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2164558a9ec3'
down_revision = 'd578ee306aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        # Add the new address column, allowing it to be NULL for existing rows
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        # Remove the old column
        batch_op.drop_column('person_to_visit')

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        # Add the new address column
        batch_op.add_column(sa.Column('last_address', sa.String(length=100), nullable=True))
        # Remove the old column
        batch_op.drop_column('last_person_to_visit')

    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        # Add the new address column, allowing it to be NULL for existing rows
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        # Remove the old column
        batch_op.drop_column('person_to_visit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        # Re-add the old column
        batch_op.add_column(sa.Column('person_to_visit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        # Drop the new column
        batch_op.drop_column('address')

    with op.batch_alter_table('visitor', schema=None) as batch_op:
        # Re-add the old column
        batch_op.add_column(sa.Column('last_person_to_visit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        # Drop the new column
        batch_op.drop_column('last_address')

    with op.batch_alter_table('request', schema=None) as batch_op:
        # Re-add the old column
        batch_op.add_column(sa.Column('person_to_visit', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        # Drop the new column
        batch_op.drop_column('address')
    # ### end Alembic commands ###