"""Tweaked Visitor log

Revision ID: 5b6972cdd989
Revises: ded1fde67853
Create Date: 2025-08-28 15:14:24.653639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6972cdd989'
down_revision = 'ded1fde67853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('check_out_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['check_out_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['check_in_by_id'], ['id'])
        batch_op.drop_column('check_out_gate')
        batch_op.drop_column('check_in_gate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_gate', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('check_out_gate', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('check_out_by_id')
        batch_op.drop_column('check_in_by_id')

    # ### end Alembic commands ###
