""" Added Separated Gate for in and out

Revision ID: 5c291682175e
Revises: 8bfebf5483fc
Create Date: 2025-08-27 21:43:48.849342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c291682175e'
down_revision = '8bfebf5483fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_gate', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('check_out_gate', sa.String(length=50), nullable=True))
        batch_op.drop_column('gate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gate', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('check_out_gate')
        batch_op.drop_column('check_in_gate')

    # ### end Alembic commands ###
