"""Added Visitor model and visitor_id foreign key to VisitorLog

Revision ID: 661cfbf4e3d9
Revises: 5f9fef6217e6
Create Date: 2025-07-05 08:05:36.680133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661cfbf4e3d9'
down_revision = '5f9fef6217e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('qr_code', sa.String(length=200), nullable=False),
    sa.Column('last_purpose', sa.String(length=200), nullable=True),
    sa.Column('last_person_to_visit', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'visitor', ['visitor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visitor_id')

    op.drop_table('visitor')
    # ### end Alembic commands ###
