"""Reset to old version by migrating

Revision ID: 8bfebf5483fc
Revises: 9e0f6fd68f6f
Create Date: 2025-08-27 20:23:21.158870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfebf5483fc'
down_revision = '9e0f6fd68f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('request_visitor_id_fkey'), type_='foreignkey')
        batch_op.drop_column('visitor_id')

    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('visitor_log_checked_out_by_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('visitor_log_approved_by_out_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('visitor_log_approved_by_in_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('visitor_log_checked_in_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['checked_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['approved_by_id'], ['id'])
        batch_op.drop_column('checked_in_by_id')
        batch_op.drop_column('approved_by_out_id')
        batch_op.drop_column('approved_by_in_id')
        batch_op.drop_column('checked_out_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_out_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approved_by_in_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approved_by_out_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('checked_in_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('visitor_log_checked_in_by_id_fkey'), 'user', ['checked_in_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('visitor_log_approved_by_in_id_fkey'), 'user', ['approved_by_in_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('visitor_log_approved_by_out_id_fkey'), 'user', ['approved_by_out_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('visitor_log_checked_out_by_id_fkey'), 'user', ['checked_out_by_id'], ['id'])
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('checked_by_id')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('request_visitor_id_fkey'), 'visitor', ['visitor_id'], ['id'])

    # ### end Alembic commands ###
