"""Added visitor_id in request

Revision ID: 9e0f6fd68f6f
Revises: e86f0f93ea03
Create Date: 2025-08-27 19:38:22.275351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e0f6fd68f6f'
down_revision = 'e86f0f93ea03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visitor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'visitor', ['visitor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('visitor_id')

    # ### end Alembic commands ###
