"""Initial migration with Request, added group_code

Revision ID: a4a4ff6e827c
Revises: b7ae73c8c871
Create Date: 2025-08-23 10:33:49.602226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a4ff6e827c'
down_revision = 'b7ae73c8c871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_code', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('group_code')

    # ### end Alembic commands ###
