"""Add visit_session_id to VisitorLog

Revision ID: ac0ec7b11c0e
Revises: 661cfbf4e3d9
Create Date: 2025-07-05 14:47:22.855936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0ec7b11c0e'
down_revision = '661cfbf4e3d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_session_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.drop_column('visit_session_id')

    # ### end Alembic commands ###
