"""added new variables in user and Visitorlog (gate. gate_role, and checked_by_id)

Revision ID: cf894b98b839
Revises: a4a4ff6e827c
Create Date: 2025-08-25 19:46:33.735120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf894b98b839'
down_revision = 'a4a4ff6e827c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gate_role', sa.String(length=50), nullable=True))

    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gate', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['checked_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gate')
        batch_op.drop_column('checked_by_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gate_role')

    # ### end Alembic commands ###
