"""Minor changes in visitorlog

Revision ID: d6dbed47b8b8
Revises: 5b6972cdd989
Create Date: 2025-08-28 16:58:46.460066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dbed47b8b8'
down_revision = '5b6972cdd989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_gate', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('check_out_gate', sa.String(length=50), nullable=True))
        batch_op.drop_constraint(batch_op.f('visitor_log_checked_by_id_fkey'), type_='foreignkey')
        batch_op.drop_column('checked_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('visitor_log_checked_by_id_fkey'), 'user', ['checked_by_id'], ['id'])
        batch_op.drop_column('check_out_gate')
        batch_op.drop_column('check_in_gate')

    # ### end Alembic commands ###
