"""Added Check_in_time and out in Visitorlog

Revision ID: ded1fde67853
Revises: 5c291682175e
Create Date: 2025-08-28 15:03:15.855435

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ded1fde67853'
down_revision = '5c291682175e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_time', postgresql.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', postgresql.TIMESTAMP(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')

    # ### end Alembic commands ###
