"""Add separate fields for check-in/out users and approvals

Revision ID: e86f0f93ea03
Revises: 8977124f4678
Create Date: 2025-08-27 19:07:51.936502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86f0f93ea03'
down_revision = '8977124f4678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('checked_out_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_in_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_out_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('visitor_log_approved_by_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('visitor_log_checked_by_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['approved_by_out_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['checked_in_by_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['approved_by_in_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['checked_out_by_id'], ['id'])
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('checked_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('visitor_log_checked_by_id_fkey'), 'user', ['checked_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('visitor_log_approved_by_id_fkey'), 'user', ['approved_by_id'], ['id'])
        batch_op.drop_column('approved_by_out_id')
        batch_op.drop_column('approved_by_in_id')
        batch_op.drop_column('checked_out_by_id')
        batch_op.drop_column('checked_in_by_id')

    # ### end Alembic commands ###
